version: '3.0'
services:
  api:
    image: lay9412206/app-python:4.0
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8888
    # ports:
    #     - 8888:8888
    hostname: "api"
    restart: always
    # LABEL:
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:layx.ddns.net"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.api == true]
    environment:
      - TZ=Asia/Taipei
    networks:
        - traefik

networks:
  traefik:
    # 加入已經存在的網路
    external: true
