version: '3.5'
services:

  mysql:
      image: lay9412206/mysql:8.0
      container_name: mysql
      build:
        context: .
        dockerfile: ./env/mysql/Dockerfile

      command: mysqld --default-authentication-plugin=mysql_native_password      
      ports:
          - 3306:3306
      environment:
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - mysql:/var/lib/mysql
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      container_name: phpmyadmin
      links: 
          - mysql:db
      ports:
          - 8080:80
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          PMA_HOST: mysql
      depends_on:
        - mysql
      # swarm 設定
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.labels.mysql == true]
      networks:
          - my_network
     
networks:
  # swarm 內部網路溝通的名稱
  my_network:
    #driver: overlay
    # 在外面的網路名稱 , name property 只有3.5版本以後有提供
    name: my_network
    # 加入已經存在的網路
    #external: true

volumes:
  mysql:
    name: mysql