version: '3.0'
services:
  scheduler:
    image: lay9412206/app-python:3.0
    hostname: "twse"
    command: python financialdata/scheduler.py
    restart: always
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.scheduler == true]
    environment:
      - TZ=Asia/Taipei
networks:
  my_network:
    # 加入已經存在的網路
    external: true
